Update dataloaders.py
Initially, incase of include class you'll recieve the following error
```
self.segments[i] = segment[j]
TypeError: only integer scalar arrays can be converted to a scalar index
```
Changing to:
```python
self.segments[i] = np.array(segment)[j]
```
you'll receive
```
TypeError: 'tuple' object does not support item assignment
```
So we need to convert also self.segments to list initially to make it work 


Signed-off-by: Mohamad Mansour <moemansour03@gmail.com>